#!/bin/bash
# Scan ~/src/*/ and emit `includeIf` blocks for any directory where a
# matching ~/.gitconfig.<dir> file exists. The generated file is included
# (unconditionally) from ~/.gitconfig.
#
# Idempotent: the output file is only rewritten when its contents change, so
# repeated runs don't churn mtimes.
set -eu -o pipefail

src="$HOME/src"
out_dir="$HOME/.gitconfig.d"
out="$out_dir/includes"
tmp="$out.tmp.$$"

mkdir -p "$out_dir"

{
  echo "# Generated by lib/gen-gitconfig-includes.sh. Do not edit by hand."
  if [[ -d "$src" ]]; then
    for dir in "$src"/*/; do
      [[ -d "$dir" ]] || continue
      name="$(basename "$dir")"
      cfg="$HOME/.gitconfig.$name"
      [[ -f "$cfg" ]] || continue
      printf '[includeIf "gitdir:~/src/%s/"]\n\tpath = ~/.gitconfig.%s\n' "$name" "$name"
    done
  fi
} > "$tmp"

if ! cmp -s "$tmp" "$out" 2>/dev/null; then
  mv "$tmp" "$out"
else
  rm -f "$tmp"
fi
